Models/Students.cs
namespace studmanagementsystemv13.Models
{
    public class Students
    {
        public int ID { get; set; }
        //public string Name { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Suffix { get; set; }
        public string StreetAdd { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public DateTime BDate { get; set; }
        public string Gender { get; set; }
        public int Pnumber { get; set; }
        public string EmailAdd { get; set; }
        public string Yearlevel { get; set; }
        public string Degree { get; set; }


    }
}

Controllers/EnrollmentController.cs
using System.Linq.Expressions;
using Google.Protobuf;
using Microsoft.AspNetCore.Mvc;
using studmanagementsystemv13.Models;

public class EnrollmentController : Controller
{

    private readonly StudentContext _studentContext;

    public EnrollmentController(StudentContext studentContext)
    {
        _studentContext = studentContext;
    }

    public IActionResult EnrollmentForm11()
    {
        return View();
    }

    public IActionResult EnrollmentForm()
    {
        return View();
    }

    public IActionResult StudentTable()
    {
        var students = _studentContext.GetStudents();
        return View(students);
    }

    [HttpGet]
    public IActionResult UpdateEnrollmentForm(int id)
    {
        var studentids = _studentContext.GetStudentsById(id);
        return View(studentids);
    }

    [HttpPost]
    public IActionResult UpdateEnrollmentForm(Students updatedstudents)
    {
        try
        {
            int ID = updatedstudents.ID;
            bool isSuccess = _studentContext.UpdateStudent(updatedstudents);

            if (isSuccess)
            {
                TempData["SuccessMessage"] = "Student information updated successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = ID;
            }
        }
        catch (Exception ex)
        {
            TempData["ErrorMessageCatch"] = $"Error: {ex.Message}";
        }

        return View(updatedstudents);
    }

    [HttpPost]
    public IActionResult DeleteStudent(int id)
    {
        try
        {
            bool isSuccess = _studentContext.DeleteStudent(id);

            if (isSuccess)
            {
                TempData["SuccessMessage"] = "Student deleted successfully!";
            }
            else
            {
                TempData["ErrorMessage"] = "Error deleting student";
            }
        }
        catch (Exception ex)
        {
            TempData["ErrorMessageCatch"] = $"Error: {ex.Message}"; 
        }
        return RedirectToAction("StudentTable");
    }
    [HttpPost]
    public IActionResult EnrollmentForm11(Students students)
    {
        bool isSuccess = _studentContext.InsertStudent(students);

        if (isSuccess)
        {
            ViewBag.IsSuccess = true;
            ViewBag.Message = "SAVE RJUDDDDDDY AY!!";
        }
        else
        {
            ViewBag.Message = "GI AHAK WALAAAAA";
        }

        return View(students);
    }


    [HttpPost]
    public IActionResult EnrollmentForm(Students students)
    {
        bool isSuccess = _studentContext.InsertStudentLang(students);

        if (isSuccess)
        {
            ViewBag.IsSuccess = true;
            ViewBag.Message = "SAVE RJUDDDDDDY AY!!";
        }
        else
        {
            ViewBag.Message = "GI AHAK WALAAAAA";
        }

        return View(students);
    }



}
   

Views/Enrollment/EnrollmentForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post">
    <div class="container">
        <h1>STUDENT FORM</h1>
        <div class="container">
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Full Name</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <input type="type" name="Lname" value="" />
                        <span class="span-text">Last Name</span>
                    </div>
                    <div class="col">
                        <input type="type" name="Fname" value="" />
                        <span class="span-text">First Name</span>
                    </div>
                    <div class="col">
                        <input type="type" name="Mname" value="" />
                        <span class="span-text">Middle Name</span>
                    </div>
                    <div class="col">
                        <input type="type" name="Suffix" value="" />
                        <span class="span-text">Suffix</span>
                    </div>
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Address</h4>
                </div>
                <div class="col row">
                    <div class="row">
                        <div>
                            <input class="input-text-size" type="type" name="StreetAdd" value="" />
                            <span class="span-text">Street Address</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input class="input-text-size" type="type" name="City" value="" />
                            <span class="span-text">City</span>
                        </div>
                        <div class="col">
                            <input class="input-text-size" type="type" name="Province" value="" />
                            <span class="span-text">State/Province</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Birth Date</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <input class="input-text-size" type="date" name="BDate" value="" />

                    </div>
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Gender</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <select class="input-text-size" name="Gender">
                            <option>Male</option>
                            <option>Female</option>
                            <option>Non-Binary</option>
                        </select>

                    </div>

                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Contact Information</h4>
                </div>
                <div class="col row">
                    <div class="row">
                        <div class="col">
                            <input type="type" name="Pnumber" value="" />
                            <span class="span-text">Phone Number</span>
                        </div>
                        <div class="col">
                            <input type="type" name="EmailAdd" value="" />
                            <span class="span-text">Email Address</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Year Level</h4>
                </div>
                <div class="col row">
                    <div class="row">
                        <div class="col">
                            <select class="input-text-size" name="Yearlevel">
                                <option>1st Year</option>
                                <option>2nd Year</option>
                                <option>3rd Year</option>
                                <option>4rd Year</option>
                                <option>5rd Year</option>
                            </select>
                            <span class="span-text">Year Level</span>
                        </div>
                        <div class="col">
                            <select class="input-text-size" name="Degree">
                                <option>BSCPe</option>
                                <option>UG</option>
                                <option>AKO</option>
                                <option>NALANG</option>
                                <option>DIAY</option>

                            </select>
                            <span class="span-text">Degree</span>
                        </div>
                    </div>
                </div>

            </div>

		</div>
        <div class="row">
            <br>
            <button id="" type="text" class="btn btn-primary">Submit</button>
        </div>

</form>

Views/Enrollment/EnrollmentForm11.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@if (TempData["SAVE RJUDDDDDDY AY!!"] != null)
{
    <script>
        alert('@TempData["SAVE RJUDDDDDDY AY!!"]');
        console.info('@TempData["SAVE RJUDDDDDDY AY!!"]');
    </script>
}
else if (TempData["GI AHAK WALAAAAA"] != null)
{
    <script>
        alert('@TempData["GI AHAK WALAAAAA"]');
        console.error('@TempData["GI AHAK WALAAAAA"]');
    </script>
}


<form method="post" action="@Url.Action("EnrollmentForm11", "Enrollment")">
    <div class="row container mt-5">
        <h1.1>Student's Name: </h1.1>
        <input type="text" class="form-control border-2" name="Name" />
    </div>
    <div class="row">
        <br>
        <button type="text" class="btn btn-primary">Submit</button>
        
    </div>
</form>

Views/Enrollment/StudentTable.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">

    <table class="table">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Middle Name
                </th>
                <th>
                    Suffix
                </th>
                <th>
                    Gender
                </th>
                <th>
                    Year Level
                </th>
                <th>
                    Degree
                </th>
                <th>
                    Actions
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var student in Model)
            {
                <tr>
                    <td>
                        @student.ID
                    </td>
                    <td>
                        @student.Lname
                    </td>
                    <td>
                        @student.Fname
                    </td>
                    <td>
                        @student.Mname
                    </td>
                    <td>
                        @student.Suffix
                    </td>
                    <td>
                        @student.Gender
                    </td>
                    <td>
                        @student.Yearlevel
                    </td>
                    <td>
                        @student.Degree
                    </td>
                    <td>
                        <form method="get" action="@Url.Action("UpdateEnrollmentForm","Enrollment", new {id = student.ID})">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                        <form method="post" action="@Url.Action("DeleteStudent", "Enrollment", new {id = student.ID})" onsubmit="return confirm('Are you sure you want to delete this student?');">
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Enrollment/UpdateEnrollmentForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}



<div class="container">

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>students is Enrolled Successfuly</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    }
    else if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <strong>Failed</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>

    }
</div>
<form method="post" action="@Url.Action("UpdateEnrollmentForm", "Enrollment")">
    <div class="container">
        <h1>STUDENT FORM</h1>
        <div class="container">
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Student Number</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <input type="number" name="ID" value="@Model.ID" />
                        <span class="span-text">Student ID</span>
                    </div>
                    
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Full Name</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <input type="text" name="Lname" value="@Model.Lname" />
                        <span class="span-text">Last Name</span>
                    </div>
                    <div class="col">
                        <input type="text" name="Fname" value="@Model.Fname" />
                        <span class="span-text">First Name</span>
                    </div>
                    <div class="col">
                        <input type="text" name="Mname" value="@Model.Mname" />
                        <span class="span-text">Middle Name</span>
                    </div>
                    <div class="col">
                        <input type="text" name="Suffix" value="@Model.Suffix" />
                        <span class="span-text">Suffix</span>
                    </div>
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Address</h4>
                </div>
                <div class="col row">
                    <div class="row">
                        <div>
                            <input class="input-text-size" type="text" name="StreetAdd" value="@Model.StreetAdd" />
                            <span class="span-text">Street Address</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <input class="input-text-size" type="text" name="City" value="@Model.City" />
                            <span class="span-text">City</span>
                        </div>
                        <div class="col">
                            <input class="input-text-size" type="text" name="Province" value="@Model.Province" />
                            <span class="span-text">State/Province</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Birth Date</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <input class="input-text-size" type="date" name="BDate" value="@Model.BDate.ToString("yyyy-MM-dd")" required />

                    </div>
                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Gender</h4>
                </div>
                <div class="col row">
                    <div class="col">
                        <select class="input-text-size" name="Gender">
                           <option>@Model.Gender</option>
                            <option>Male</option>
                            <option>Female</option>
                            <option>Non-Binary</option>
                        </select>

                    </div>

                </div>
            </div>
            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Contact Information</h4>
                </div>
                <div class="col row">
                    <div class="row">
                        <div class="col">
                            <input type="number" name="Pnumber" value="@Model.Pnumber" />
                            <span class="span-text">Phone Number</span>
                        </div>
                        <div class="col">
                            <input type="text" name="EmailAdd" value="@Model.EmailAdd" />
                            <span class="span-text">Email Address</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row border">
                <div class="col-3">
                    <h4 class="display-text">Year Level</h4>
                </div>
                <div class="col row">
                    <div class="row">
                        <div class="col">
                            <select class="input-text-size" name="Yearlevel" value="@Model.Yearlevel">
                               <option>@Model.Yearlevel</option>
                                <option>1st Year</option>
                                <option>2nd Year</option>
                                <option>3rd Year</option>
                                <option>4rd Year</option>
                                <option>5rd Year</option>
                            </select>
                            <span class="span-text">Year Level</span>
                        </div>
                        <div class="col">
                            <select class="input-text-size" name="Degree" value="@Model.Degree">
                                <option>@Model.Degree</option>
                                <option>BSCPe</option>
                                <option>UG</option>
                                <option>AKO</option>
                                <option>NALANG</option>
                                <option>DIAY</option>

                            </select>
                            <span class="span-text">Degree</span>
                        </div>
                    </div>
                </div>

            </div>

        </div>
        <div class="row">
            <br>
            <button type="submit" class="btn btn-primary">Update</button>
        </div>

</form>